export const eeaCountries = [
  {
    value: 'Albania',
    label: 'Albania',
    group: ['EEA32', 'EEA33', 'EEA39', 'Pan-Europe'],
  },
  {
    value: 'Austria',
    label: 'Austria',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Belgium',
    label: 'Belgium',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Bosnia and Herzegovina',
    label: 'Bosnia and Herzegovina',
    group: ['EFTA4', 'Pan-Europe'],
  },
  {
    value: 'Bulgaria',
    label: 'Bulgaria',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Croatia',
    label: 'Croatia',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Cyprus',
    label: 'Cyprus',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'Pan-Europe'],
  },
  {
    value: 'Czechia',
    label: 'Czechia',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU25',
      'EU27',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Denmark',
    label: 'Denmark',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU15', 'EU25', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Estonia',
    label: 'Estonia',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Finland',
    label: 'Finland',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'France',
    label: 'France',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Germany',
    label: 'Germany',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Greece',
    label: 'Greece',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Hungary',
    label: 'Hungary',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Iceland',
    label: 'Iceland',
    group: ['EEA32', 'EEA33', 'EEA39', 'EFTA4', 'Pan-Europe'],
  },
  {
    value: 'Ireland',
    label: 'Ireland',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Italy',
    label: 'Italy',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Kosovo (UNSCR 1244/99)',
    label: 'Kosovo (UNSCR 1244/99)',
    group: ['EEA32', 'EEA33', 'EEA39'],
  },
  {
    value: 'Latvia',
    label: 'Latvia',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Liechtenstein',
    label: 'Liechtenstein',
    group: ['EEA32', 'EEA33', 'EEA39', 'EFTA4', 'Pan-Europe'],
  },
  {
    value: 'Lithuania',
    label: 'Lithuania',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Luxembourg',
    label: 'Luxembourg',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Malta',
    label: 'Malta',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Montenegro',
    label: 'Montenegro',
    group: ['EEA32', 'EEA33', 'EEA39', 'Pan-Europe'],
  },
  {
    value: 'Netherlands',
    label: 'Netherlands',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'North Macedonia',
    label: 'North Macedonia',
    group: ['EEA32', 'EEA33', 'EEA39', 'Pan-Europe'],
  },
  {
    value: 'Norway',
    label: 'Norway',
    group: ['EEA32', 'EEA33', 'EEA39', 'EFTA4', 'Pan-Europe'],
  },
  {
    value: 'Poland',
    label: 'Poland',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Portugal',
    label: 'Portugal',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Romania',
    label: 'Romania',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Serbia',
    label: 'Serbia',
    group: ['EEA32', 'EEA33', 'EEA39', 'Pan-Europe'],
  },
  {
    value: 'Slovakia',
    label: 'Slovakia',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Slovenia',
    label: 'Slovenia',
    group: ['EEA32', 'EEA33', 'EEA39', 'EU25', 'EU27', 'EU28', 'Pan-Europe'],
  },
  {
    value: 'Spain',
    label: 'Spain',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Sweden',
    label: 'Sweden',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
  {
    value: 'Switzerland',
    label: 'Switzerland',
    group: ['EEA32', 'EEA33', 'EEA39', 'EFTA4', 'Pan-Europe'],
  },
  {
    value: 'Turkey',
    label: 'Turkey',
    group: ['EEA32', 'EEA33', 'EEA39', 'Pan-Europe'],
  },
  {
    value: 'United Kingdom',
    label: 'United Kingdom',
    group: [
      'EEA32',
      'EEA33',
      'EEA39',
      'EU15',
      'EU25',
      'EU27',
      'EU28',
      'Pan-Europe',
    ],
  },
];

export const eeaGroups = [
  { label: 'EEA32', value: 'EEA32' },
  { label: 'EEA33', value: 'EEA33' },
  { label: 'EEA39', value: 'EEA39' },
  { label: 'EFTA4', value: 'EFTA4' },
  { label: 'EU15', value: 'EU15' },
  { label: 'EU25', value: 'EU25' },
  { label: 'EU27', value: 'EU27' },
  { label: 'EU28', value: 'EU28' },
  { label: 'Pan-Europe', value: 'pan-europe' },
  { label: 'Biogeographical regions', value: 'biogeographical regions' },
];
